neural:
  model: deepseek/deepseek-chat-v3-0324:free
  api:
    key:

spring:
  config:
    import: application-private.yml
  thymeleaf:
    cache: false

tg:
  url: https://web.telegram.org/k/#

logging:
  level:
    org:
      lakas:
        personalproject:
          selenium:
            debug

server:
  port: 8082