neural:
  api:
    key: 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

spring:
  thymeleaf:
    cache: false