neural:
  model: qwen/qwen2.5-vl-72b-instruct:free
  api:
    key:

spring:
  config:
    import: application-private.yml
  thymeleaf:
    cache: false

tg:
  url: https://web.telegram.org/k/#

logging:
  level:
    org:
      lakas:
        personalproject:
          neural:
            debug

server:
  port: 8082