neural:
  model: deepseek/deepseek-chat-v3-0324:free
  api:
    key:

spring:
  config:
    import: application-private.yml
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
tg:
  url: https://web.telegram.org/k/#

logging:
  level:
    org:
      lakas:
        personalproject:
          selenium:
            debug

server:
  port: 8082