neural:
  model: google/gemini-2.5-pro-exp-03-25:free
  api:
    key:

spring:
  config:
    import: application-private.yml
  thymeleaf:
    cache: false

tg:
  url: https://web.telegram.org/k/#

#logging:
#  level:
#    org:
#      lakas:
#        personalproject:
#          neural:
#            debug

server:
  port: 8082